### PR TITLE
Improve error messages for missing required keys

### PR DESCRIPTION
**Pull request by alexkalderimis**
# More specific messages for required keys

Improves the error messages when required keys are missing, by listing precisely
which ones are missing.

Also:

- improves dev experience by allowing use of `debugger` by default
- improves editor experience by improving rubocop integrations

### CODE REVIEW

**Comment by alexkalderimis** [comment]
I removed the offending `debug` dev dependency, so as not to break `jruby` and `truffleruby`.

This should be ready for review.

**Comment by alexkalderimis** [comment]
Thanks for your reactions @skryukov - could I ask you for a review and release of a new version? Would you like me to update this branch to bump the version?

**Comment by skryukov** [comment]
@alexkalderimis it's fine as it is, I'll release a new version later today 👍

**Comment by skryukov** [comment]
Released in `0.2.4`, thanks Alex!

**Comment by alexkalderimis** [comment]
> Released in `0.2.4`, thanks Alex!

Thanks very much!

**Pull request merged**
